import React, { useState } from 'react';
import CreatableSelect from 'react-select/creatable';

const options = [
  { value: 'apple', label: 'Apple' },
  { value: 'banana', label: 'Banana' },
  { value: 'orange', label: 'Orange' },
];

const PrivacyPolicy = () => {
    const [selectedOptions, setSelectedOptions] = useState([]);

    const handleChange = (selectedOptions) => {
      setSelectedOptions(selectedOptions);
    };
  
    // Custom function to handle new option creation
    const handleCreateOption = (inputValue) => {
      const newValue = { value: inputValue.toLowerCase(), label: inputValue };
      setSelectedOptions([...selectedOptions, newValue]);
      return newValue; // Return the new option
    };
    return (
        <div className="mx-2 md:mx-8 text-gray-800">
 <CreatableSelect
      value={selectedOptions}
      onChange={handleChange}
      options={options}
      isMulti
      isClearable
      onCreateOption={handleCreateOption} // Handle creation of new options
    />
            <h1 className="text-3xl font-bold mb-8">Privacy Policy</h1>
            <p className="mb-4"><strong>Last updated:</strong> March 31, 2024</p>
            <p className="mb-4">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
            <p className="mb-4">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" rel="noreferrer" className="text-blue-500 hover:underline">Privacy Policy Generator</a>.</p>
            
            <h2 className="text-2xl font-bold mt-8 mb-4">Interpretation and Definitions</h2>
            <p className="mb-4">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            
            <h3 className="text-xl font-bold mt-6 mb-2">Definitions</h3>
            <ul className="list-disc pl-8 mb-8">
                <li><strong>Account:</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                <li><strong>Affiliate:</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                <li><strong>Company:</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Hope For Everybody LLC, 9525 Manchester Lane Bay Shore, NY 11706.</li>
                <li><strong>Cookies:</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                <li><strong>Country:</strong> refers to: New York, United States</li>
                <li><strong>Device:</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                <li><strong>Personal Data:</strong> is any information that relates to an identified or identifiable individual.</li>
                <li><strong>Service:</strong> refers to the Website.</li>
                <li><strong>Service Provider:</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                <li><strong>Usage Data:</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                <li><strong>Website:</strong> refers to Made Behind Bars, accessible from <a href="https://mbb-e-commerce.web.app/" target="_blank" rel="noreferrer" className="text-blue-500 hover:underline">https://mbb-e-commerce.web.app/</a></li>
                <li><strong>You:</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
            
            {/* Collecting and Using Your Personal Data */}
            {/* Add the rest of your privacy policy content here */}
            
            <h2 className="text-2xl font-bold mt-8 mb-4">Contact Us</h2>
            <ul>
                <li className="mb-2">By email: <a href="mailto:mbbadmin@gmail.com" className="text-blue-500 hover:underline">mbbadmin@gmail.com</a></li>
                <li className="mb-2">By phone number: <a href="tel:+15247379174" className="text-blue-500 hover:underline">5247379174</a></li>
            </ul>
        </div>
    );
};

export default PrivacyPolicy;